$(document).ready(function() {
  document.getElementById("testarea").innerHTML = "HELLO THERE JADIAHGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
  console.log("loading");
});